name: Authenticate

on:
  push:
    branches:
    - main
    - 'branch-*'
  pull_request:
    branches:
    - '**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    timeout-minutes: 60
    name: Run Authentication tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update rust toolchain
      run: rustup update

    - name: Start the cluster
      run: docker compose -f test/cluster/docker-compose-passauth.yml up -d

    - name: Run tests
      run: SCYLLA_URI=172.43.0.2 RUST_LOG=trace cargo test authenticate_superuser -- custom_authentication --ignored

    - name: Stop the cluster
      if: ${{ always() }}
      run: docker compose -f test/cluster/docker-compose-passauth.yml stop

    - name: Print the cluster logs
      if: ${{ always() }}
      run: docker compose -f test/cluster/docker-compose-passauth.yml logs
