# This workflow builds the book with documentation and runs book tests
name: Book

on:
  push:
    branches:
    - main
    - 'branch-*'
  pull_request:
    branches:
    - '**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug scylladb" --health-interval 5s --health-retries 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        # We can't use cache here, or mdbook will complain about multiple candidates for dependency.
        cache: false
    - name: Install mdbook
      run: cargo install mdbook --no-default-features
    - name: Build the project
      run: cargo build --examples
    - name: Build the book
      run: mdbook build docs
    - name: Run book tests
      run: mdbook test -L target/debug/deps docs
