name: Serverless

on:
  push:
    branches:
    - main
    - 'branch-*'
  pull_request:
    branches:
    - '**'
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Install scylla-ccm
        run: pip3 install https://github.com/scylladb/scylla-ccm/archive/master.zip

      - name: Create serverless cluster
        run: |
          ccm create serverless -i 127.0.1. -n 1 --scylla -v release:6.2
          ccm start  --sni-proxy --sni-port 7777
      - name: Update rust toolchain
        run: rustup update
      - name: Check
        run: cargo check
      # Cloud-related feature sets.   
      - name: Cargo check with unstable-cloud and openssl-x features
        run: cargo check --all-targets -p scylla --features "unstable-cloud" --features "openssl-010"
      - name: Cargo check with unstable-cloud and rustls-x features
        run: cargo check --all-targets -p scylla --features "unstable-cloud" --features "rustls-023"
      - name: Cargo check with unstable-cloud, openssl-x and rustls-x features
        run: cargo check --all-targets -p scylla --features "unstable-cloud" --features "openssl-010" --features "rustls-023"

      - name: Run cloud-openssl example
        run: cargo run --example cloud-openssl -- $HOME/.ccm/serverless/config_data.yaml
      - name: Run cloud-rustls example
        run: cargo run --example cloud-rustls -- $HOME/.ccm/serverless/config_data.yaml
      - name: Run cloud tests
        run: CLOUD_CONFIG_PATH=$HOME/.ccm/serverless/config_data.yaml RUSTFLAGS="--cfg scylla_cloud_tests" RUST_LOG=trace cargo test

      - name: Remove serverless cluster
        run: ccm remove serverless